### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by mistvan** [vitorzachi/tomcat-runner#3]
I just prepared better logo and wanted to push it as pull request, but I do not have required privileges. So here you have new logo 
![tomcat](https://user-images.githubusercontent.com/814958/43371294-0e23b71e-938f-11e8-9e07-1d5535a31da0.png)

**Comment by vitorzachi** [comment]
Hi,
Thanks for contribution.
Your suggestion will be updated today.

Regards
