### ISSUE TITLE
Any plan of releasing latest version

### ISSUE THREAD

**Issue by debdeepmajila** [vitorzachi/tomcat-runner#6]
Hi,

I really enjoy this plugin. It really works out of the box.
But, after IntelliJ 2020.1 update, I had to disable it for the issue which is fixed now.
Is there any plan to release it to Jetbrains anytime soon?

Thanks

**Comment by vitorzachi** [comment]
Hi.
I have good news :)
Today, the new version of the plugin has been updated and is in moderation by IntelliJ team.

**Comment by debdeepmajila** [comment]
Latest version is available in JetBrains plugin center
And it works like a charm. Thank you so much for the plugin.
